repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.1
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.900 # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [--install-types, --check-untyped-defs]
        exclude: ^(tests/|sandbox/)
        additional_dependencies:
          [
            python-telegram-bot == 20.7,
            pydantic-settings == 2.1.0,
            loguru == 0.7.2,
            redis == 5.0.1,
          ]
  - repo: https://github.com/python-poetry/poetry
    rev: "1.3.0" # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
