version: '3.9'

services:
  redis:
    image: redis:7.2.3
    container_name: redis
    command: redis-server --appendonly yes
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./storage:/data